name: project
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  path:
  sqflite:
  sqflite_common_ffi: ^2.2.5
  audioplayers: ^1.0.1
  image_picker: ^0.8.5+2
  crypto: ^3.0.3
  flutter_dotenv: ^5.2.1
  http: ^0.13.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/musics/
   - assets/capas/
  # fonts:
  
